---
# Source

# Warning
- color: "ee0701"
  description: "Categorize bug reports."
  name: ":warning: bug"
- color: "0366d6"
  description: "Pull requests that update a dependency file"
  name: ":robot: dependencies"

# Highlight
- color: "0e8a16"
  description: "Good for newcomers."
  name: ":fire: good first issue"
- color: "0e8a16"
  description: "Extra attention is needed."
  name: ":fire: help wanted"
- color: "0075ca"
  description: "Improvements or additions to documentation"
  name: ":memo: documentation"

# Cancel
- color: "dddddd"
  description: "This issue or pull request already exists."
  name: ":pray: duplicate"
- color: "dddddd"
  description: "This will not be worked on."
  name: ":zzz: wontfix"

# Size
- color: "cfd3d7"
  description: "Extra Small size issue or PR."
  name: "size/XS"
- color: "cfd3d7"
  description: "Small size issue or PR."
  name: "size/S"
- color: "cfd3d7"
  description: "Medium size issue or PR."
  name: "size/M"
- color: "cfd3d7"
  description: "Large size issue or PR."
  name: "size/L"
- color: "cfd3d7"
  description: "Extra Large size issue or PR."
  name: "size/XL"
