checksumBehavior: reset

enableGlobalCache: false

nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.6.0.cjs

packageExtensions:
  'eslint-plugin-testing-library@*':
    peerDependencies:
      typescript: '*'
  'eslint-plugin-jest@*':
    peerDependencies:
      typescript: '*'
  '@commitlint/load@*':
    peerDependencies:
      typescript: '*'
      '@types/node': '*'
  '@commitlint/cli@*':
    peerDependencies:
      typescript: '*'
      '@types/node': '*'
  '@commitlint/cz-commitlint@*':
    peerDependencies:
      typescript: '*'
      '@types/node': '*'
  'cz-conventional-changelog@*':
    peerDependencies:
      typescript: '*'
      '@types/node': '*'
  'commitizen@*':
    peerDependencies:
      typescript: '*'
      '@types/node': '*'