checksumBehavior: update

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.7.0.cjs

packageExtensions: {
  "@commitlint/cz-commitlint@*": {
    peerDependencies: {
      typescript: "*",
      "@types/node": "*",
    },
  },
  "@commitlint/cli@*": {
    peerDependencies: {
      typescript: "*",
      "@types/node": "*",
    },
  },
  "@commitlint/load@*": {
    peerDependencies: {
      typescript: "*",
      "@types/node": "*",
    },
  },
  "@storybook/addon-docs@*": {
    peerDependencies: {
      "@types/react": "*",
    },
  },
  "@storybook/addon-essentials@*": {
    peerDependencies: {
      "@types/react": "*",
    },
  },
  "@storybook/core@*": {
    peerDependencies: {
      storybook: "*",
    },
  },
  "cz-conventional-changelog@*": {
    peerDependencies: {
      typescript: "*",
      "@types/node": "*",
    },
  },
  "commitizen@*": {
    peerDependencies: {
      typescript: "*",
      "@types/node": "*",
    },
  },
  "eslint-plugin-jest@*": {
    peerDependencies: {
      typescript: "*",
    },
  },
  "eslint-plugin-storybook@*": {
    peerDependencies: {
      typescript: "*",
    },
  },
  "eslint-plugin-testing-library@*": {
    peerDependencies: {
      typescript: "*",
    },
  },
  "tunnel-rat@*": {
    peerDependencies: {
      react: "*",
    },
  }
}
