packages:
  - apps/*
  - packages/*
catalog:
  "@types/node": ^22
  autoprefixer: ^10
  eslint: ^9
  lucide-react: ^0
  prettier: ^3
  react-hook-form: ^7
  ts-node: ^10
  turbo: ^2
  typescript: ^5
  webpack: ^5
catalogs:
  commitlint19:
    "@commitlint/cli": ^19
    "@commitlint/config-conventional": ^19
    "@commitlint/cz-commitlint": ^19
    "@commitlint/format": ^19
    "@commitlint/types": ^19
  jest29:
    "@types/jest": ^29
    jest: ^29
    jest-environment-jsdom: ^29
    ts-jest: ^29
  next15:
    "@next/bundle-analyzer": ^15
    "@next/eslint-plugin-next": ^15
    next: ^15
  postcss:
    postcss: ^8
    postcss-load-config: ^6
    postcss-loader: ^8
  react19:
    "@types/react": ^19
    "@types/react-dom": ^19
    react: ^19
    react-dom: ^19
  storybook8:
    "@storybook/addon-a11y": ^8
    "@storybook/addon-essentials": ^8
    "@storybook/addon-interactions": ^8
    "@storybook/addon-links": ^8
    "@storybook/blocks": ^8
    "@storybook/nextjs": ^8
    "@storybook/react": ^8
    "@storybook/react-webpack5": ^8
    "@storybook/test": ^8
    storybook: ^8
  tailwind:
    tailwind-merge: ^3
    tailwindcss: ^3
    tailwindcss-animate: ^1
