name: Playwright Tests
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v5
        with:
          node-version: 24.x
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build web app
        run: pnpm build --filter @juun/web
      - name: Install Playwright Browsers
        run: pnpm --filter @juun/web exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm --filter @juun/web exec playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: apps/web/playwright-report/
          retention-days: 30
