name: Monorepo Release

on:
  push:
    branches:
      - main
    paths:
      - '**/package.json'
  workflow_dispatch:
    inputs:
      version:
        description: 'Override version number (optional)'
        required: false

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version info
        id: version
        run: |
          # Use manually provided version or extract from root package.json
          if [ "${{ github.event.inputs.version }}" != "" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=$(node -p "require('./package.json').version")
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          # Create a simple release summary
          echo "# Release v$VERSION" > release_notes.md
          echo "" >> release_notes.md
          echo "Updated packages:" >> release_notes.md

          # List changed package.json files in the latest commit
          CHANGED_PKGS=$(git diff-tree --no-commit-id --name-only -r HEAD | grep package.json | grep -v "node_modules" || echo "No package changes detected")
          echo "\`\`\`" >> release_notes.md
          echo "$CHANGED_PKGS" >> release_notes.md
          echo "\`\`\`" >> release_notes.md

          # Add commit message for context
          echo "" >> release_notes.md
          echo "Commit: ${{ github.event.head_commit.message || 'Manual release' }}" >> release_notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          body_path: release_notes.md
          draft: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
