name: Sync to Vercel Branch
on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - main
jobs:
  sync-branch:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Check if vercel branch exists
        id: check-branch
        run: |
          git fetch origin
          if git branch -r | grep -q "origin/vercel"; then
            echo "Branch exists"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Branch does not exist"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create vercel branch if it doesn't exist
        if: steps.check-branch.outputs.exists == 'false'
        run: |
          # Configure Git user
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

          git checkout -b vercel
          git push -u origin vercel

      - name: Sync main to vercel branch
        if: steps.check-branch.outputs.exists == 'true'
        run: |
          # Configure Git user
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

          # Checkout the main branch first
          git checkout main

          # Save the current .yarnrc.yml from vercel branch
          git checkout origin/vercel -- .yarnrc.yml
          mv .yarnrc.yml .yarnrc.yml.vercel

          # Checkout vercel branch
          git checkout vercel
          git pull origin vercel

          # Merge main into vercel, taking main's version for all files except .yarnrc.yml
          git merge main -X theirs --no-commit --no-ff

          # Restore the saved .yarnrc.yml from vercel branch
          mv .yarnrc.yml.vercel .yarnrc.yml
          git add .yarnrc.yml

          # Complete the merge
          git commit -m "Merge main into vercel, preserving .yarnrc.yml"

          # Push to vercel branch
          git push origin vercel
